routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'] )->name('home');


Route::get('/register', [AuthController::class, 'getRegister'])->name('register.form');
Route::post('/register', [AuthController::class, 'postRegister'])->name('register.store');
Route::get('/login', [AuthController::class, 'getLogin'])->name('login');
Route::post('/login', [AuthController::class, 'authenticate'])->name('login.authenticate');
Route::get('/logout', [AuthController::class, 'logout'])->name('register.logout')->middleware("auth");

Route::get('/posts', [PostController::class, 'index'])->name('posts.list');
Route::get('/post/create', [PostController::class, 'getCreate'])->middleware('auth');
Route::post('/post/create', [PostController::class, 'create'])->middleware('auth')->name('post.create');
Route::get('/post/{uuid}', [PostController::class, 'getPost'])->name('post.get');
Route::get('/post/edit/{uuid}',[PostController::class, 'getEdit']);
Route::post('/post/edit/{uuid}',[PostController::class, 'edit'])->name('post.edit');
Route::get('/post/delete/{uuid}', [PostController::class, 'destroy'])->name('post.delete');
Route::post('/comments/{uuid}', [CommentController::class, 'makeComment'])->middleware('auth')->name('comment.make');
Route::get("/comments/{post_id}", [CommentController::class, 'getAll'])->name('comments.get');
Route::delete('/comments/', [CommentController::class, 'delete'])->middleware('auth')->name('comment.delete');


Route::name('profile.')->group( function (){
    Route::get('/profile/me', [ProfileController::class, 'index'])->name('me')->middleware('auth');
    Route::get('/profile/me/edit', [ProfileController::class, 'getEdit'])->name('me.edit')->middleware('auth');
    Route::post('/profile/me/edit', [ProfileController::class, 'edit'])->name('edit')->middleware('auth');

    Route::get('/profile/{uuid}', [ProfileController::class, 'userProfile'])->name('user');
});

app/Http/Controllers/ProfileController.php
<?php

namespace App\Http\Controllers;

use App\Services\Contracts\IPostService;
use App\Services\Contracts\IUserService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class ProfileController extends Controller
{
    private  IUserService $_userService;
    private IPostService $_postService;
    public function __construct(IUserService $userService, IPostService $postService){
        $this->_userService = $userService;
        $this->_postService = $postService;
    }

   public function index(){
        $id = Auth::user()->id;
        $posts = $this->_userService->getUserPosts($id);
        return view('pages.profile.me', ['posts' => $posts]);

   }

   public function userProfile($id){
        //busca o usuário pelo id
        $user = $this->_userService->getById($id);

        //busca os posts desse usuario
        $posts = $this->_userService->getUserPosts($id);
        //injeta os dados na view
        return view('pages.profile.user',['user'=>$user, 'posts'=>$posts]);
   }

   public function getEdit(){
       $user = $this->_userService->getById(Auth::user()->id);
       return view('pages.profile.edit', ['user'=>$user]);
   }

    public function edit(Request $request){
try {
    //valida os dados
    $request->validate([
        "firstName" => "  string",
        "lastName" => "  string",
        "email" => "  email",
    ]);
    $data = $request->only('firstName', 'lastName', 'email');
    if ($request->hasFile('image')) { //VERIFICA SE ALGUMA IMAGEM FOI ENVIADA
        $request->validate([
            'image' => '|image|mimes:png,jpg,jpeg|max:2048' //VALIDA A IMAGEM
        ]);
        $filename = $request->image->getClientOriginalName();
        $imageName = time() . '-' . str_replace(' ', '-', $filename); // GERA UM NOME ÚNICO PARA ELA
        $data['image'] = $imageName; //SALVA NO OBJETO DE DADOS
        $request->image->move(public_path('images'), $imageName); //SALVA A IMAGEM NA PUBLIC
    }
    $this->_userService->update($data, Auth::user()->id); //CHAMA O SERVIÇO DE UPDATE
    return redirect(route('profile.me'));
}catch (\Exception $e){
    dd($e);
}
    }

}

resources/views/pages/profile/edit.blade.php
@extends('layout.default')
@section('content')
 <div class="container">
    <form method="post" action="{{route('profile.edit')}}" enctype="multipart/form-data">
        @csrf
     <!-- Email input -->
        <div class="form-outline mb-4">
            <input value="{{$user->firstName}}" type="text" id="name" class="form-control" name="firstName" />
            <label class="form-label" for="name">Nome</label>
        </div>

        <div class="form-outline mb-4">
            <input value="{{$user->lastName}}" type="text" id="lastName" class="form-control" name="lastName" />
            <label class="form-label" for="lastName">Sobrenome</label>
        </div>

     <div class="form-outline mb-4">
         <input value="{{$user->email}}" type="email" id="email" class="form-control" name="email" />
         <label class="form-label" for="email">Email</label>
     </div>


        <div class="form-outline mb-4">
            <label class="form-label" for="avatar">Profile Image</label>
            <input type="file" class="form-control" name="image" id="avatar" />
        </div>

     <!-- Submit button -->
     <button type="submit" class="btn btn-primary btn-block">Editar conta</button>
 </form>
 </div>
@stop

resources/views/pages/profile/me.blade.php
@extends('layout.default')

@section('content')

    <section style="background-color: #eee;">
        <div class="container py-5">
            <div class="row">
                <div class="col">
                    <nav aria-label="breadcrumb" class="bg-light rounded-3 p-3 mb-4">
                        <ol class="breadcrumb mb-0">
                            <li class="breadcrumb-item"><a href="/">Home</a></li>
                            <li class="breadcrumb-item"><a href="javascript:void(0);">User</a></li>
                            <li class="breadcrumb-item active" aria-current="page">User Profile</li>
                        </ol>
                    </nav>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-4">
                    <div class="card mb-4">
                        <div class="card-body text-center">
                            <img src="{{asset('images/'.Auth::user()->image)}}" alt="avatar"
                                 class="rounded-circle img-fluid" style="width: 150px;">
                            <h5 class="my-3">{{Auth::user()->getFullName()}}</h5>
{{--                            <p class="text-muted mb-1">Full Stack Developer</p>--}}
{{--                            <p class="text-muted mb-4">Bay Area, San Francisco, CA</p>--}}
                            <div class="d-flex justify-content-center mb-2">
                                <a href="{{route('profile.me.edit')}}" type="button" class="btn btn-primary">Editar perfil</a>
{{--                                <button type="button" class="btn btn-outline-primary ms-1">Message</button>--}}
                            </div>
                        </div>
                    </div>
{{--                    <div class="card mb-4 mb-lg-0">--}}
{{--                        <div class="card-body p-0">--}}
{{--                            <ul class="list-group list-group-flush rounded-3">--}}
{{--                                <li class="list-group-item d-flex justify-content-between align-items-center p-3">--}}
{{--                                    <i class="fas fa-globe fa-lg text-warning"></i>--}}
{{--                                    <p class="mb-0">https://mdbootstrap.com</p>--}}
{{--                                </li>--}}
{{--                                <li class="list-group-item d-flex justify-content-between align-items-center p-3">--}}
{{--                                    <i class="fab fa-github fa-lg" style="color: #333333;"></i>--}}
{{--                                    <p class="mb-0">mdbootstrap</p>--}}
{{--                                </li>--}}
{{--                                <li class="list-group-item d-flex justify-content-between align-items-center p-3">--}}
{{--                                    <i class="fab fa-twitter fa-lg" style="color: #55acee;"></i>--}}
{{--                                    <p class="mb-0">@mdbootstrap</p>--}}
{{--                                </li>--}}
{{--                                <li class="list-group-item d-flex justify-content-between align-items-center p-3">--}}
{{--                                    <i class="fab fa-instagram fa-lg" style="color: #ac2bac;"></i>--}}
{{--                                    <p class="mb-0">mdbootstrap</p>--}}
{{--                                </li>--}}
{{--                                <li class="list-group-item d-flex justify-content-between align-items-center p-3">--}}
{{--                                    <i class="fab fa-facebook-f fa-lg" style="color: #3b5998;"></i>--}}
{{--                                    <p class="mb-0">mdbootstrap</p>--}}
{{--                                </li>--}}
{{--                            </ul>--}}
{{--                        </div>--}}
{{--                    </div>--}}
                </div>
                <div class="col-lg-8">
                    <div class="card mb-4">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-3">
                                    <p class="mb-0">Full Name</p>
                                </div>
                                <div class="col-sm-9">
                                    <p class="text-muted mb-0">{{Auth::user()->getFullName()}}</p>
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <p class="mb-0">Email</p>
                                </div>
                                <div class="col-sm-9">
                                    <p class="text-muted mb-0">{{Auth::user()->email}}</p>
                                </div>
                            </div>
{{--                            <hr>--}}
{{--                            <div class="row">--}}
{{--                                <div class="col-sm-3">--}}
{{--                                    <p class="mb-0">Phone</p>--}}
{{--                                </div>--}}
{{--                                <div class="col-sm-9">--}}
{{--                                    <p class="text-muted mb-0">(097) 234-5678</p>--}}
{{--                                </div>--}}
{{--                            </div>--}}
{{--                            <hr>--}}
{{--                            <div class="row">--}}
{{--                                <div class="col-sm-3">--}}
{{--                                    <p class="mb-0">Mobile</p>--}}
{{--                                </div>--}}
{{--                                <div class="col-sm-9">--}}
{{--                                    <p class="text-muted mb-0">(098) 765-4321</p>--}}
{{--                                </div>--}}
{{--                            </div>--}}
{{--                            <hr>--}}
{{--                            <div class="row">--}}
{{--                                <div class="col-sm-3">--}}
{{--                                    <p class="mb-0">Address</p>--}}
{{--                                </div>--}}
{{--                                <div class="col-sm-9">--}}
{{--                                    <p class="text-muted mb-0">Bay Area, San Francisco, CA</p>--}}
{{--                                </div>--}}
{{--                            </div>--}}
                        </div>
                    </div>
                    <div class="row">
                        @foreach($posts as $post)
                            <div class="col-md-4" style="margin-bottom: 16px;">
                                <div class="card text-center border border-primary shadow-0 ">
                                    <div class="bg-image hover-overlay ripple" data-mdb-ripple-color="light">
                                        <img src="{{asset('images/'.$post->banner)}}" class="img-fluid" />
                                        <a href="#!">
                                            <div class="mask" style="background-color: rgba(251, 251, 251, 0.15)"></div>
                                        </a>
                                    </div>
                                    <div class="card-header">{{$post->author->getFullName()}}</div>
                                    <div class="card-body">
                                        <h5 class="card-title">{{$post->title}}</h5>
                                        <p class="card-text text-truncate">
                                            {{$post->content}}
                                        </p>
                                    <div class="d-flex" style="gap: 5px; flex-wrap: wrap; justify-content: center">
                                        <a href="/post/{{$post->id}}" type="button" class="btn btn-primary">Ver detalhe</a>
                                        @auth
                                            @if($post->author->id == \Illuminate\Support\Facades\Auth::User()->id)
                                                <a href="/post/edit/{{$post->id}}" type="button" class="btn btn-primary">Editar</a>

                                            @endif
                                        @endauth
                                    </div>
                                    </div>
                                    <div class="card-footer">{{$post->created_at->isoFormat('d/m/Y')}}</div>
                                </div>
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </section>

@stop

resources/views/pages/profile/user.blade.php
@extends('layout.default')

@section('content')

    <section style="background-color: #eee;">
        <div class="container py-5">
            <div class="row">
                <div class="col">
                    <nav aria-label="breadcrumb" class="bg-light rounded-3 p-3 mb-4">
                        <ol class="breadcrumb mb-0">
                            <li class="breadcrumb-item"><a href="/">Home</a></li>
                            <li class="breadcrumb-item"><a href="javascript:void(0);">User</a></li>
                            <li class="breadcrumb-item active" aria-current="page">User Profile</li>
                        </ol>
                    </nav>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-4">
                    <div class="card mb-4">
                        <div class="card-body text-center">
                            <img src="{{asset('images/'.$user->image)}}" alt="avatar"
                                 class="rounded-circle img-fluid" style="width: 150px;">
                            <h5 class="my-3">{{$user->getFullName()}}</h5>
{{--                            <p class="text-muted mb-1">Full Stack Developer</p>--}}
{{--                            <p class="text-muted mb-4">Bay Area, San Francisco, CA</p>--}}
                            <div class="d-flex justify-content-center mb-2">
{{--                                <button type="button" class="btn btn-primary">Follow</button>--}}
{{--                                <button type="button" class="btn btn-outline-primary ms-1">Message</button>--}}
                            </div>
                        </div>
                    </div>
                    {{--                    <div class="card mb-4 mb-lg-0">--}}
                    {{--                        <div class="card-body p-0">--}}
                    {{--                            <ul class="list-group list-group-flush rounded-3">--}}
                    {{--                                <li class="list-group-item d-flex justify-content-between align-items-center p-3">--}}
                    {{--                                    <i class="fas fa-globe fa-lg text-warning"></i>--}}
                    {{--                                    <p class="mb-0">https://mdbootstrap.com</p>--}}
                    {{--                                </li>--}}
                    {{--                                <li class="list-group-item d-flex justify-content-between align-items-center p-3">--}}
                    {{--                                    <i class="fab fa-github fa-lg" style="color: #333333;"></i>--}}
                    {{--                                    <p class="mb-0">mdbootstrap</p>--}}
                    {{--                                </li>--}}
                    {{--                                <li class="list-group-item d-flex justify-content-between align-items-center p-3">--}}
                    {{--                                    <i class="fab fa-twitter fa-lg" style="color: #55acee;"></i>--}}
                    {{--                                    <p class="mb-0">@mdbootstrap</p>--}}
                    {{--                                </li>--}}
                    {{--                                <li class="list-group-item d-flex justify-content-between align-items-center p-3">--}}
                    {{--                                    <i class="fab fa-instagram fa-lg" style="color: #ac2bac;"></i>--}}
                    {{--                                    <p class="mb-0">mdbootstrap</p>--}}
                    {{--                                </li>--}}
                    {{--                                <li class="list-group-item d-flex justify-content-between align-items-center p-3">--}}
                    {{--                                    <i class="fab fa-facebook-f fa-lg" style="color: #3b5998;"></i>--}}
                    {{--                                    <p class="mb-0">mdbootstrap</p>--}}
                    {{--                                </li>--}}
                    {{--                            </ul>--}}
                    {{--                        </div>--}}
                    {{--                    </div>--}}
                </div>
                <div class="col-lg-8">
                    <div class="card mb-4">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-3">
                                    <p class="mb-0">Full Name</p>
                                </div>
                                <div class="col-sm-9">
                                    <p class="text-muted mb-0">{{$user->getFullName()}}</p>
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <p class="mb-0">Email</p>
                                </div>
                                <div class="col-sm-9">
                                    <p class="text-muted mb-0">{{$user->email}}</p>
                                </div>
                            </div>
                            {{--                            <hr>--}}
                            {{--                            <div class="row">--}}
                            {{--                                <div class="col-sm-3">--}}
                            {{--                                    <p class="mb-0">Phone</p>--}}
                            {{--                                </div>--}}
                            {{--                                <div class="col-sm-9">--}}
                            {{--                                    <p class="text-muted mb-0">(097) 234-5678</p>--}}
                            {{--                                </div>--}}
                            {{--                            </div>--}}
                            {{--                            <hr>--}}
                            {{--                            <div class="row">--}}
                            {{--                                <div class="col-sm-3">--}}
                            {{--                                    <p class="mb-0">Mobile</p>--}}
                            {{--                                </div>--}}
                            {{--                                <div class="col-sm-9">--}}
                            {{--                                    <p class="text-muted mb-0">(098) 765-4321</p>--}}
                            {{--                                </div>--}}
                            {{--                            </div>--}}
                            {{--                            <hr>--}}
                            {{--                            <div class="row">--}}
                            {{--                                <div class="col-sm-3">--}}
                            {{--                                    <p class="mb-0">Address</p>--}}
                            {{--                                </div>--}}
                            {{--                                <div class="col-sm-9">--}}
                            {{--                                    <p class="text-muted mb-0">Bay Area, San Francisco, CA</p>--}}
                            {{--                                </div>--}}
                            {{--                            </div>--}}
                        </div>
                    </div>
                    <div class="row">
                        @foreach($posts as $post)
                            <div class="col-md-4" style="margin-bottom: 16px;">
                                <div class="card text-center border border-primary shadow-0 ">
                                    <div class="bg-image hover-overlay ripple" data-mdb-ripple-color="light">
                                        <img src="{{asset('images/'.$post->banner)}}" class="img-fluid" />
                                        <a href="#!">
                                            <div class="mask" style="background-color: rgba(251, 251, 251, 0.15)"></div>
                                        </a>
                                    </div>
                                    <div class="card-header">{{$post->author->getFullName()}}</div>
                                    <div class="card-body">
                                        <h5 class="card-title">{{$post->title}}</h5>
                                        <p class="card-text text-truncate">
                                            {{$post->content}}
                                        </p>
                                        <div class="d-flex" style="gap: 5px; flex-wrap: wrap; justify-content: center">
                                            <a href="/post/{{$post->id}}" type="button" class="btn btn-primary">Ver detalhe</a>
                                            @auth
                                                @if($post->author->id == \Illuminate\Support\Facades\Auth::User()->id)
                                                    <a href="/post/edit/{{$post->id}}" type="button" class="btn btn-primary">Editar</a>

                                                @endif
                                            @endauth
                                        </div>
                                    </div>
                                    <div class="card-footer">{{$post->created_at->isoFormat('d/m/Y')}}</div>
                                </div>
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </section>

@stop